#*+-------------------------------------------------------------------+
#*| # © Copyright IBM Corp. 2025                                      |
#*| # This playbook is tested with ACC 1.2.6                          |
#*+-------------------------------------------------------------------+

- name: ACC Standalone playbook, run by ACC-admin, for ACC-admin actions
  hosts: localhost
  gather_facts : true
  vars_files:
    - admin_vars.yaml

  pre_tasks:
  - name: Reminder- Export ACC admin credentials
    pause:
      prompt: |
        Before running this playbook, please export credentials:
        
        export ACC_ADMIN_USER=<admin_username>
        export ACC_ADMIN_DEFAULT_PASSWORD=<admin_old_password>
        export ACC_ADMIN_PASSWORD=<admin_new_password>
        export ACC_OWNER_DEFAULT_PASSWORD=<owner_default_password>

        Press Ctrl+C now to cancel if you haven't done this.
        The playbook will continue shortly.
      seconds: 5

  vars_prompt:
    - name: run_init
      prompt: "Do you want to initialize ACC with Standalone Mode? (yes/no)"
      private: no
      default: "yes"

  tasks:

    - name: 01 - Get Initialize status
      ansible.builtin.uri:
        url: "{{ acc_ip }}/init"
        body:
          hmc_managed: "{{ hmc_managed }}"
          credentials:
            username: "{{ cc_admin_user }}"
            password: "{{ cc_admin_old_password}}"
        body_format: json
        method: GET
        return_content: true
        validate_certs: false
      register: init_response

    - name: Printing the response of init
      debug:
        msg: 
          - "{{ init_response.json}}"

    - name: 03 - Get authentication token from the ACC as admin
      ansible.builtin.uri:
        url: "{{ acc_ip }}/user/token"
        body:
          username: "{{ cc_admin_user }}"
          password: "{{ cc_admin_password }}"
        body_format: json
        method: POST
        return_content: true
        validate_certs: false
      register: auth_response

    - name: Printing the response of authentication
      debug:
        msg: 
          - "{{ auth_response.json.access_token }}"

    - name: Extract the admin token
      set_fact:
        access_token: "{{ auth_response.json.access_token }}"

    - name: 05 - Get list of CPCs attached to the HMC
      ansible.builtin.uri:
        url: "{{ acc_ip }}/cpcs"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: application/json
        validate_certs: false
      register: response

    - name: Printing the available CPCs
      debug:
        msg: "{{ response.json }}"

    - name: 06 - Get CPC resources of CPC defined in admin_vars.yaml
      ansible.builtin.uri:
        url: "{{ acc_ip }}/cpcs/{{ z_machine_name }}/resource"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: application/json
        validate_certs: false
      register: response

    - name: Printing the CPC resources
      debug:
        msg: "{{ response.json }}"
