#*+-------------------------------------------------------------------+
#*| # © Copyright IBM Corp. 2025                                      |
#*| # This playbook is tested with ACC 1.2.6                          |
#*+-------------------------------------------------------------------+

- name: ACC Standalone playbook, run by ACC-owner, for ACC-owner actions
  hosts: localhost
  gather_facts : true
  vars_files:
    - owner_vars.yaml

  pre_tasks:
  - name: Reminder - Export appliance-owner credentials
    pause:
      prompt: |
        Before running this playbook, please export appliance-owner credentials:

        export ACC_OWNER_DEFAULT_PASSWORD=<owner_default_password>
        export ACC_OWNER_PASSWORD=<owner_new_password>

        Press Ctrl+C now to cancel if you haven't done this.
        The playbook will continue shortly.
      seconds: 5

  tasks:
    - name: 00 - As an appliance-owner, update the password (remove this if already done)
      tags: owner
      ansible.builtin.uri:
        url: "{{ acc_ip }}/user"
        body:
          username: "{{ cc_owner_user }}"
          old_password: "{{ cc_owner_default_password}}"
          new_password: "{{ cc_owner_password }}"
        body_format: json
        method: PUT
        return_content: true
        validate_certs: false

